# Site settings
title: Thompson Highland Homeowners Association
email: board@thha.org
description: > # this means to ignore newlines until "baseurl:"
  Thompson Highland Homeowners Association<br/>
  PMB #824<br/>
  515 NW Saltzman Road<br/>
  Portland, OR 97229<br/>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thhaorg.github.io" # the base hostname & protocol for your site
app:
  board:
    alan: 'Alan Ark'
    cary: 'Cary Williams'
    lori: 'Lori Quiring'
    mike: 'Mike Mitlehner'
    pat: 'Pat Goodell'
    powell: 'Powell Quiring'
    sara: 'Sara Ark'
    paul: 'Paul Cummings'
    heather: 'Heather Pool'
    dana: 'Dana Rodman'

# Build settings
markdown: kramdown
